<?php

use Drupal\node\NodeInterface;

/**
 * Implement hook_preprocess_page.
 *
 * @param $variables
 *
 * @return void
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function day_infinite_scroll_next_node_preprocess_page(&$variables) {
  // Node.
  /** @var Drupal\node\Entity\Node $node */
  $node = \Drupal::routeMatch()->getParameter('node');
  // Get langcode.
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  // Format url langcode variable.
  $url_langcode = $language == 'uk' ? '' : '/' . $language;
  // Get logged in.
  $logged_in = \Drupal::currentUser()->isAuthenticated();


  // Functionality to load the next post.
  if ($node instanceof NodeInterface) {
    if (!$logged_in) {
      $libraries['#attached']['library'][] = 'core/drupal.ajax';
      render($libraries);
    }

    $variables['#attached']['library'][] = 'day_infinite_scroll_next_node/main-scripts';

    $node_created_time = $node->getCreatedTime();
//    $query = \Drupal::entityQuery('node');
//    $next = $query->condition('type', $node->getType())
//      ->condition('status', 1)
//      ->condition('langcode', $language)
//      ->condition('created', $node_created_time, '<')
//      ->sort('created', 'DESC')
//      ->range(0, 1)
//      ->execute();

    $query = \Drupal::database()->select('node_field_data', 'nfd')
      ->fields('nfd', ['nid'])
      ->condition('type', $node->getType())
      ->condition('status', 1)
      ->condition('langcode', $language)
      ->condition('created', $node_created_time, '<')
      ->orderBy('created', 'DESC')
      ->range(0, 1);
    $next_nid = $query->execute()->fetchField();

    // Pass next post link to variables.
    if (!empty($next_nid)) {
      $next_node_url = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $next_nid);

      $variables['next_node_id'] = $next_nid;
      $variables['next_node_url'] = $GLOBALS['base_url'] . $url_langcode . $next_node_url;
    }
  }
}
