<?php

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Link;
use Drupal\views_infinite_scroll\Plugin\views\pager\InfiniteScroll;

/**
 * Implement hook_preprocess_views_view_field().
 *
 * @param $variables
 *
 * @return void
 * @throws InvalidPluginDefinitionException
 * @throws PluginNotFoundException
 */
function day_hooks_preprocess_views_view_field(&$variables) {
  /** @var Drupal\node\NodeStorageInterface $node_storage */
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  /** @var Drupal\taxonomy\TermStorageInterface $taxonomy_storage */
  $taxonomy_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  // Get current langcode.
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $view = $variables['view'];
  $field = $variables['field'];
  $row = $variables['row'];

  // Mark hot news to tabs news blocks.
  if ($view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_3' ||
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_4' ||
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_5' ||
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_6' ||
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_7' ||
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'block_8') {

    /** @var \Drupal\node\Entity\Node $node */
    $node = $node_storage->load($row->nid);
    $field_tag_news = $node->get('field_tag_news')->getValue();

    $created = $view->field['created']->original_value;
    $title = $view->field['title']->original_value;

    $tag_news_array = [];
    foreach ($field_tag_news as $key => $tag_news) {
      /** @var Drupal\taxonomy\Entity\Term $term */
      if ($term = $taxonomy_storage->load($tag_news["target_id"])) {
        if ($term->hasField('field_hot_theme')) {
          $tag_news_array[$term->getName()] = $term->get('field_hot_theme')->value != NULL ? $term->get('field_hot_theme')->value : 0;
        }
      }
    }

    $hot_news = '';
    if (in_array(1, $tag_news_array)) {
      $hot_news = 'class=hot-new';
    }

    $markup = [
      '#type' => 'inline_template',
      '#template' => '<div {{ hot_news }}>
                        <p>{{ created }}</p>
                        {{ title }}
                       </div>',
      '#context' => [
        'created' => $created,
        'title' => $title,
        'hot_news' => $hot_news,
      ],
    ];

    $variables['output'] = $markup;
  }

  // Add main tags to '/news' page.
  if (
    $view->storage->id() == 'news' && $field->field == 'nothing' && $view->current_display == 'page_1' ||
    $view->storage->id() == 'last_news_block' && $field->field == 'nothing' && $view->current_display == 'block_1' ||
    $view->storage->id() == 'search_via_search_api' && $field->field == 'nothing' && $view->current_display == 'page_1'
  ) {

    // Get row object.
    /** @var \Drupal\Core\Entity\Plugin\DataType\EntityAdapter $row_object */
    $row_object = $row->_object ?? '';

    // Load node.
    /** @var \Drupal\node\Entity\Node $node */
    $node = $row->_entity ?? $row_object->getEntity();

    // Get node field news tags value.
    $field_tag_news = '';
    if ($node->hasField('field_tag_news')) {
      $field_tag_news = $node->get('field_tag_news')->getValue();
    }

    // Get images views field values.
    $field_op_main_image = $view->field['field_op_main_image']->original_value ?? NULL;
    $field_main_image_big = $view->field['field_main_image_big']->original_value ?? NULL;

    // Get views formatted field value.
    $created = $view->field['created']->original_value;
    $title = $view->field['title']->original_value;
    $main_image = $field_op_main_image ?? $field_main_image_big;


    // Get main tags.
    if (!empty($field_tag_news)) {
      $news_tags_array = [];
      foreach ($field_tag_news as $tag_news) {
        /** @var Drupal\taxonomy\Entity\Term $term */
        if ($term = $taxonomy_storage->load($tag_news['target_id'])) {
          /** @var Drupal\taxonomy\Entity\Term $translation_term */
          $translation_term = \Drupal::service('entity.repository')->getTranslationFromContext($term);

          if (isset($translation_term->getTranslationLanguages()[$langcode])) {
            if ($translation_term->hasField('field_main_tag')) {
              $main_tag = $translation_term->get('field_main_tag')->value;

              if ($main_tag) {
                $news_tags_array[] = Link::createFromRoute($translation_term->getName(), 'entity.taxonomy_term.canonical', ['taxonomy_term' => $translation_term->id()]);
              }
            }
          }
        }
      }
    }

    $tag_news = $news_tags_array[0] ?? NULL;

    $template =
      '<li class="news-item">
           <article>
            {{ field_main_image_big }}
            <div>
             <div>
               <p>{{ created }} </p>
               {% if tag_news %} <strong>{{ tag_news }}</strong> {% endif %}
             </div>
             <h2>
               {{ title }}
             </h2>
            </div>
          </article>
        </li>';

    $markup = [
      '#type' => 'inline_template',
      '#template' => $template,
      '#context' => [
        'created' => $created,
        'title' => $title,
        'field_main_image_big' => $main_image,
        'tag_news' => $tag_news,
      ],
    ];

    $variables['output'] = $markup;
  }

  // Add longread marks tags to '/newspaper' page.
  if ($view->storage->id() == 'main_section_newspaper' && $field->field == 'nothing' && $view->current_display == 'page_2') {

    // Load node.
    /** @var \Drupal\node\Entity\Node $node */
    $node = $node_storage->load($row->nid);

    // Get views formatted field value.
    $link_to_node = $view->field['view_node']->original_value;
    $title = $view->field['title']->original_value;
    $created = $view->field['created_1']->original_value;
    $main_image = $view->field['field_op_main_image']->original_value;
    $section_term = $view->field['field_op_section_term']->original_value;


    // Check if current node from Longread content type.
    $is_longread = '';
    if ($node->getType() == 'longread_article') {
      $is_longread = t('Special topic');
    }


    $templates = [
      'main_section_newspaper' =>
        '<li class="article-item">
          <article>
             <a href="{{ link_to_node }}">
               <img src="{{ field_op_main_image }}" alt>
             </a>
              <div>
                 <div>
                    <p class="date">{{ created_date }}</p>
                    <strong>{{ field_op_section_term }}</strong>
                    {% if longread_mark %} <p class="longread-mark">{{ longread_mark }}</p> {% endif %}
                 </div>
                 <h2>
                   <a href="{{ link_to_node }}">{{ title }}</a>
                 </h2>
              </div>
          </article>
        </li>',
    ];

    $markup = [
      '#type' => 'inline_template',
      '#template' => $templates[$view->storage->id()],
      '#context' => [
        'created_date' => $created,
        'link_to_node' => $link_to_node,
        'title' => $title,
        'field_op_main_image' => $main_image,
        'field_op_section_term' => $section_term,
        'longread_mark' => $is_longread,
      ],
    ];

    $variables['output'] = $markup;
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function day_hooks_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->id() == 'blocks_for_video_page' && $view->getDisplay()->display['id'] == 'block_3' && $view->getDisplay()->isPagerEnabled() && !empty($vars['rows'])) {
    $pager = $view->getPager();
    if ($pager instanceof InfiniteScroll) {
      $vars['rows']['#theme_wrappers']['container']['#attributes']['class'][] = 'videoPage__box _icon-play _icon-brand _link-brand article-grouped-wrap-20';
      $vars['rows']['#theme_wrappers']['container']['#attributes']['id'][] = 'filter';
    }
  }
}

/**
 * Implement hook_form_alter.
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 * @return void
 */
function day_hooks_form_alter(&$form, $form_state, $form_id) {
  if (strpos($form_id, 'approval_poll_view_form_') !== false) {
    $form['actions']['vote']['#attributes']['class'][] = 'button--vote';
    $form['actions']['result']['#attributes']['class'][] = 'button--result';
    $form['actions']['cancel']['#attributes']['class'][] = 'button--cancel';
  }
}
