name: day.kyiv-d9
recipe: drupal9
config:
  php: '7.4'
  webroot: web/
  via: nginx
  database: mysql:5.7
  drush: true
  xdebug: true
  drupal: true
  config:
    database: mysql
    php: .lando/php.ini

proxy:
  mailhog:
    - mail.day.kyiv-d9.lndo.site
  phpmyadmin:
    - pma.day.kyiv-d9.lndo.site

services:
  appserver:
    overrides:
      environment:
        DB_HOST: database
        DB_NAME: drupal9
        DB_USER: drupal9
        DB_PASSWORD: drupal9
        DB_ROOT_PASSWORD: ""
        DB_DRIVER: mysql
        PHP_IDE_CONFIG: 'serverName=day.kyiv-d9.lndo.site'
        DRUSH_OPTIONS_URI: 'http://day.kyiv-d9.lndo.site'
        COMPOSE_HTTP_TIMEOUT: 3600
        PWD: '/app'
    build:
      - composer install --ansi --optimize-autoloader --quiet --no-interaction
  daydrupal7:
    type: mysql:5.7
    creds:
      user: drupal7
      password: drupal7
      database: daydrupal7
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - daydrupal7

tooling:
  phpcs:
    service: appserver
    description: 'Run phpcs'
    cmd:
      - phpcs

  phpcbf:
    service: appserver
    description: 'Run phpcbf'
    cmd:
      - /app/vendor/bin/phpcbf
