display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Фильтр
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
          tags:
            previous: '‹ предыдущая'
            next: 'следующая ›'
            first: '« первая'
            last: 'последняя »'
      fields:
        commerce_order_bulk_form:
          action_title: 'С выделенным'
        order_number:
          separator: ', '
        placed:
          label: Дата
          separator: ', '
        type:
          label: Тип
          separator: ', '
        store_id:
          separator: ', '
        uid:
          separator: ', '
        mail:
          label: Email
          separator: ', '
        state:
          label: Состояние
          separator: ', '
        total_price__number:
          label: Итого
          separator: ', '
        operations:
          label: Операции
      filters:
        type:
          expose:
            label: Тип
        state:
          expose:
            label: Состояние
  page_1:
    display_title: Страница
