display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Search
      empty:
        area:
          content:
            value: "<p>На жаль, за Вашим запитом нічого не знайдено</p>\r\n"
            format: full_html
      filters:
        search_api_fulltext:
          expose:
            placeholder: 'Enter a search word'
