_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: uk
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  advpoll: 0
  ajax_loader: 0
  automated_cron: 0
  better_exposed_filters: 0
  better_status_messages: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  block_title_link: 0
  breakpoint: 0
  captcha: 0
  checklistapi: 0
  ckeditor: 0
  ckeditor_config: 0
  ckeditor_day_blockquote: 0
  color: 0
  colorbox: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  context: 0
  context_ui: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  day_custom_breadcrumbs: 0
  day_hooks: 0
  day_infinite_scroll_next_node: 0
  day_tabs_news_block: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  eva: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fivestar: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  juicebox: 0
  language: 0
  libraries: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_skip_on_404: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  node_revision_delete: 0
  options: 0
  other_view_filter: 0
  page_cache: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  poll: 0
  profile: 0
  quick_node_clone: 0
  quickedit: 0
  quicktabs: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  rest: 0
  scheduled_publish: 0
  search_api: 0
  search_api_db: 0
  search_api_fast: 0
  seo_checklist: 0
  serialization: 0
  shortcut: 0
  simplify_menu: 0
  state_machine: 0
  statistics: 0
  superfish: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  term_reference_tree: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  twig_vardumper: 0
  ultimate_cron: 0
  update: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_index_hint: 0
  views_infinite_scroll: 0
  views_infinite_scroll_with_pager: 0
  views_rss: 0
  views_rss_core: 0
  views_ui: 0
  votingapi: 0
  webform: 0
  webform_migrate: 0
  webform_node: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  tvi: 15
  twigsuggest: 100
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  day_theme: 0
profile: standard
